### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by atauln** [Naquino14/t-com#1]
I cloned this repo and ran it, and I immediately realized that this piece of software has a MASSIVE FLAW. It's written in C#! Please consider rewriting this in C. I, and the rest of your audience, is still awaiting greatness.

**Comment by Naquino14** [comment]
Dear @atauln, upon observation, you appear to be using an unstable operating system that can't handle the robustness of this application. I suggest you follow [https://www.microsoft.com/software-download/windows11](this guide) to fix this fatal problem as soon as possible. I will now be closing this issue.
