### ISSUE TITLE
Proper Respect on Fora

### ISSUE THREAD

**Issue by atauln** [Naquino14/t-com#2]
Dear Mr. @Naquino14, 

I recently posted on this forum due to an issue I was having with your software. It was my belief that this was a location of union and mutual respect. I asked a question which I thought to be completely reasonable, but was, completely unexpectedly, blasted in the face with a nonsensical, unrelated response! Not to mention, the issue was closed, so I could not even fight my case!

I understand that you are quite busy maintaining your other repositories, but I ask that you consider being slightly more respectfully to those that trust your software and want it to grow. Please consider what I said in #1, I think it is really the only rational decision to make in this scenario.

**Comment by Naquino14** [comment]
Mans on Chat-GPT 💀💀

**Comment by atauln** [comment]
This only furthers my point, I personally wrote this message out, and yet even the repository _maintainer_ does not have time to even fathom the possibility that his constituents may be this enraged about his lack of proper respect.

**Comment by Naquino14** [comment]
Dear Mr. @atauln. My apologies for the lack of respect. I would like to respectfully tell you that your issues on this code repository have been marked as spam to the GitHub team, for they are nonconstructive, and spam. With all due respect, I suggest that you refrain from posting further irrelevant issues, or there will be disciplinary consequences.
